### ISSUE TITLE
Can't create a translation for readme file

### ISSUE THREAD

**Issue by MCarlomagno** [starknet-edu/starknet-cairo-101#11]
Hi! today I've been working on the spanish translation for the `README` file. But seems that there is not a very clear workflow about how to contribute in this case.

By the documentation:
```markdown
### Contributing
This project can be made better and will evolve as StarkNet matures. Your contributions are welcome! Here are things that you can do to help:

- Create a branch with a translation to your language
- Correct bugs if you find some
- Add an explanation in the comments of the exercise if you feel it needs more explanation
- Add exercises showcasing your favorite Cairo feature
```
I forked the project, then created a `spanish` local branch, then translated the `README` file and now I don't know how can I do the PR to a new branch called `spanish`.

**Comment by MCarlomagno** [comment]
I did a workaround creating a README-ES.md file on the main branch instead of trying to create a new branch for the translation here is the PR

https://github.com/starknet-edu/starknet-cairo-101/pull/12

**Comment by 0xLucqs** [comment]
Created the branch for you

**Comment by MCarlomagno** [comment]
Done, [PR here](https://github.com/starknet-edu/starknet-cairo-101/pull/13) :)
